export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const DELETE_USER_FROM_GROUP = 'DELETE_USER_FROM_GROUP';
export const ADD_SELECTED_USERS = 'ADD_SELECTED_USERS';
